# Generated by Django 5.1.4 on 2024-12-09 18:29

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to=authentication.models.upload_to_directory),
        ),
    ]
